"use client"

import useSWR from "swr"
import { useRouter } from "next/navigation"
import { Activity, ArrowRight, Loader2, ShieldAlert } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { SiteHeader } from "@/components/site-header"
import { cn } from "@/lib/utils"
import type { Incident, Posture } from "@/lib/types"
import { postureClasses, postureLabel, severityLabel, timeAgo } from "@/lib/ui-helpers"

const fetcher = (url: string) => fetch(url).then((r) => r.json())

export default function IncidentsPage() {
  const router = useRouter()
  const { data, isLoading } = useSWR<{ incidents: Incident[] }>("/api/incidents", fetcher)
  const incidents = data?.incidents || []

  return (
    <div className="min-h-screen">
      <SiteHeader />
      <main className="mx-auto max-w-7xl px-4 py-8 md:px-6">
        <div className="mb-6 flex flex-wrap items-end justify-between gap-4">
          <div className="flex flex-col gap-1">
            <h1 className="text-2xl font-semibold md:text-3xl">Incident command log</h1>
            <p className="max-w-2xl text-sm text-muted-foreground">
              Every decision generated by RecallZero, including posture, confidence, exposure, and
              the current operator status.
            </p>
          </div>
          <Button variant="secondary" onClick={() => router.push("/?skipSplash=1")} className="gap-1.5">
            Analyze new signal
            <ArrowRight className="h-4 w-4" />
          </Button>
        </div>

        {isLoading && (
          <div className="flex items-center justify-center py-24">
            <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
          </div>
        )}

        {!isLoading && incidents.length === 0 && (
          <Card className="border-dashed">
            <CardContent className="flex flex-col items-center gap-3 py-16 text-center">
              <Activity className="h-6 w-6 text-muted-foreground" />
              <h2 className="text-lg font-semibold">No incidents yet</h2>
              <p className="max-w-sm text-balance text-sm text-muted-foreground">
                No incidents are in the command log yet. Pull a connector signal or analyze a new
                recall signal to create the first record.
              </p>
              <div className="flex flex-wrap justify-center gap-2">
                <Button onClick={() => router.push("/?skipSplash=1")} className="gap-1.5">
                  Analyze first signal
                  <ArrowRight className="h-4 w-4" />
                </Button>
                <Button variant="secondary" onClick={() => router.push("/connectors")}>Pull connector signal</Button>
              </div>
            </CardContent>
          </Card>
        )}

        {!isLoading && incidents.length > 0 && (
          <div className="grid gap-3">
            {incidents.map((incident) => (
              <button
                key={incident.id}
                onClick={() => router.push(`/incidents/${incident.id}`)}
                className="group rounded-xl border border-border bg-card p-4 text-left transition-colors hover:bg-secondary/35"
              >
                <div className="flex flex-wrap items-start justify-between gap-4">
                  <div className="flex min-w-0 flex-1 flex-col gap-2">
                    <div className="flex flex-wrap items-center gap-2">
                      <PostureChip posture={incident.decision.posture} />
                      <span className="rounded-md border border-border bg-secondary/50 px-2 py-1 text-xs font-medium text-muted-foreground">
                        {incident.status}
                      </span>
                      {incident.acknowledged && (
                        <span className="rounded-md border border-success/40 bg-success/10 px-2 py-1 text-xs font-medium text-success">
                          Acknowledged
                        </span>
                      )}
                    </div>
                    <div className="min-w-0">
                      <h2 className="truncate text-sm font-semibold md:text-base">{incident.title}</h2>
                      <p className="truncate text-xs text-muted-foreground">
                        {incident.source} · {severityLabel(incident.decision.severity)}
                      </p>
                    </div>
                  </div>

                  <div className="grid min-w-48 grid-cols-2 gap-3 text-right sm:grid-cols-3">
                    <Metric label="Confidence" value={`${incident.decision.confidenceScore}/100`} />
                    <Metric label="Exposure" value={incident.decision.exposureEstimate} />
                    <Metric label="Updated" value={timeAgo(incident.updatedAt)} />
                  </div>
                </div>
              </button>
            ))}
          </div>
        )}
      </main>
    </div>
  )
}

function PostureChip({ posture }: { posture: Posture }) {
  return (
    <span className={cn("rounded-md border px-2 py-1 text-xs font-medium", postureClasses(posture))}>
      <ShieldAlert className="mr-1 inline h-3 w-3" />
      {postureLabel(posture)}
    </span>
  )
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex flex-col gap-0.5">
      <span className="text-[11px] uppercase tracking-wide text-muted-foreground">{label}</span>
      <span className="truncate font-mono text-xs font-semibold text-foreground">{value}</span>
    </div>
  )
}