import { NextResponse } from "next/server"
import { getIncident, getAuditTrail, recordAction } from "@/lib/db"
import { getCurrentSession } from "@/lib/workspace-context"
import type { Incident, AuditEvent } from "@/lib/types"

function fmt(ts: number): string {
  return new Date(ts).toISOString().replace("T", " ").slice(0, 19) + " UTC"
}

function buildPacket(incident: Incident, audit: AuditEvent[]): string {
  const d = incident.decision
  const lines: string[] = []
  lines.push("RECALLZERO — INCIDENT AUDIT PACKET")
  lines.push("=".repeat(60))
  lines.push(`Incident ID:      ${incident.id}`)
  lines.push(`Title:            ${incident.title}`)
  lines.push(`Status:           ${incident.status}`)
  lines.push(`Source:           ${incident.source}`)
  lines.push(`Lot reference:    ${incident.lotReference || "—"}`)
  lines.push(`Affected regions: ${(incident.affectedRegions || []).join(", ") || "—"}`)
  lines.push(`Signals folded:   ${incident.signalCount || 1}`)
  lines.push(`Opened:           ${fmt(incident.createdAt)}`)
  lines.push(`Last updated:     ${fmt(incident.updatedAt)}`)
  lines.push(`Generated:        ${fmt(Date.now())}`)
  lines.push("")
  lines.push("CURRENT RECOMMENDATION")
  lines.push("-".repeat(60))
  lines.push(`Posture:          ${d.posture}`)
  lines.push(`Confidence:       ${d.confidence} (${d.confidenceScore}/100)`)
  lines.push(`Severity:         Class ${d.severity}`)
  lines.push(`Financial exposure: ${d.exposureEstimate}`)
  lines.push(`Headline:         ${d.headline}`)
  lines.push("")
  lines.push("Rationale:")
  lines.push(`  ${d.rationale}`)
  lines.push("")
  lines.push("Evidence gaps blocking confidence:")
  d.evidenceGaps.forEach((g) => lines.push(`  • [${g.kind}] ${g.label} — ${g.detail}`))
  lines.push("")
  lines.push("Conditions that would change the recommendation:")
  d.flipConditions.forEach((f) => lines.push(`  • If ${f.condition} → ${f.flipsTo}`))
  lines.push("")
  lines.push("Delay risk:")
  lines.push(`  Trajectory: ${d.delayRisk.trajectory} · ~${d.delayRisk.hoursUntilCritical}h until materially worse`)
  lines.push(`  ${d.delayRisk.narrative}`)
  lines.push("")
  lines.push("FULL DECISION AUDIT TRAIL")
  lines.push("-".repeat(60))
  // Oldest first for a chronological record
  ;[...audit].reverse().forEach((e) => {
    lines.push(`[${fmt(e.createdAt)}] ${e.actor} — ${e.kind.toUpperCase()}${e.action ? ` (${e.action})` : ""}`)
    lines.push(`  ${e.summary}`)
  })
  lines.push("")
  lines.push("=".repeat(60))
  lines.push("This packet is a system-of-record export generated by RecallZero.")
  lines.push("Every decision, revision, and operator action is timestamped and immutable.")
  return lines.join("\n")
}

export async function GET(req: Request, { params }: { params: Promise<{ incidentId: string }> }) {
  try {
    const { incidentId } = await params
    const session = await getCurrentSession()
    if (!session) return NextResponse.json({ error: "Sign in before exporting audit packets." }, { status: 401 })
    const workspaceId = session.workspaceId
    const incident = await getIncident(incidentId, workspaceId)
    if (!incident) {
      return NextResponse.json({ error: "Incident not found." }, { status: 404 })
    }
    const audit = await getAuditTrail(incidentId, workspaceId)
    const packet = buildPacket(incident, audit)

    // Record the export itself on the audit trail (defensibility).
    await recordAction({
      incidentId,
      action: "export",
      summary: "Audit packet exported for compliance / regulatory record.",
      actor: "Operator",
      workspaceId,
    })

    return new NextResponse(packet, {
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Content-Disposition": `attachment; filename="recallzero-audit-${incidentId}.txt"`,
      },
    })
  } catch (error) {
    console.error("[recallzero] export error:", error)
    return NextResponse.json({ error: "Could not generate the audit packet." }, { status: 500 })
  }
}
